//! # Woof 🐕
//!
//! An extremely fast Go linter and code formatter written in Rust.
//!
//! ## Features
//!
//! - ⚡ **Blazing Fast** — Parallel processing with Rayon for maximum throughput
//! - 🔧 **Auto-Fix** — Automatically fix common issues
//! - 🎯 **Go-Native** — Designed specifically for Go code patterns
//! - 📊 **Multiple Output Formats** — Text, JSON, and GitHub Actions annotations
//! - 📝 **Configurable** — TOML-based configuration
//! - 🧪 **Tree-sitter** — Precise parsing with tree-sitter
//!
//! ## Quick Start
//!
//! ### As a CLI tool
//!
//! ```bash
//! # Install
//! cargo install woofmt
//!
//! # Check current directory
//! woof check .
//!
//! # Check with auto-fix
//! woof check . --fix
//!
//! # Format files
//! woof format .
//! ```
//!
//! ### As a library
//!
//! ```toml
//! [dependencies]
//! woofmt = "0.1.0"
//! ```
//!
//! ```rust,no_run
//! use woofmt::{lint_path, format_path, config::Config};
//!
//! // Load configuration
//! let config = Config::load(None).unwrap();
//!
//! // Lint a file or directory
//! let diagnostics = lint_path("./src", &config).unwrap();
//! for diag in diagnostics {
//!     println!("{}: {}", diag.severity, diag.message);
//! }
//!
//! // Format a file or directory
//! let result = format_path("./src", false, &config).unwrap();
//! println!("Formatted {} files", result.files_formatted);
//! ```
//!
//! ## Architecture
//!
//! The library is organized into several modules:
//!
//! | Module | Description |
//! |--------|-------------|
//! | [`linter`] | Linting engine and diagnostic generation |
//! | [`formatter`] | Code formatting engine |
//! | [`rules`] | Lint rules implementation |
//! | [`config`] | Configuration handling |
//! | [`parser`] | Parser pool for efficient AST parsing |
//!
//! ## Lint Rules
//!
//! | Code | Name | Description | Severity |
//! |------|------|-------------|----------|
//! | E001 | unused-import | Unused import statements | Warning |
//! | E101 | line-too-long | Line exceeds maximum length | Error |
//! | E201 | trailing-whitespace | Lines with trailing whitespace | Warning |
//! | E301 | empty-block | Empty code blocks | Error |
//! | E401 | mixed-tabs-spaces | Mixed indentation | Error |
//! | D001 | exported-missing-doc | Missing documentation | Warning |
//!
//! ## Performance
//!
//! Woof is designed for speed:
//!
//! - **Parallel processing** — Uses Rayon for data parallelism
//! - **Parser pool** — Reuses tree-sitter parsers to avoid initialization overhead
//! - **Zero-copy I/O** — Memory-mapped file reading where possible
//! - **Memory arena** — Efficient memory allocation for AST nodes
//!
//! ## Configuration
//!
//! Create a `woof.toml` file in your project root:
//!
//! ```toml
//! [global]
//! target_go_version = "1.21"
//! respect_gitignore = true
//! exclude = ["vendor/", "*.gen.go"]
//!
//! [linter]
//! select = ["E", "W", "D"]
//! ignore = ["E101"]
//!
//! [formatter]
//! use_tabs = true
//! tab_width = 4
//! line_length = 120
//! ```
//!
//! ## Links
//!
//! - [Repository](https://github.com/GWinfinity/woof)
//! - [crates.io](https://crates.io/crates/woofmt)
//! - [Issues](https://github.com/GWinfinity/woof/issues)
//!
//! ## License
//!
//! Licensed under the Apache License 2.0.

pub mod arena;
pub mod cli;
pub mod config;
pub mod fixer;
pub mod formatter;
pub mod io; // Zero-copy I/O
pub mod linter;
pub mod linter_optimized;
pub mod linter_profiled {
    //! Profiled linting utilities for performance analysis
    pub use super::linter::profiled::*;
}
pub mod linter_parallel {
    //! Parallel linting utilities
    pub use super::linter::parallel::*;
}
pub mod logger;
pub mod parser;
pub mod rules;

// Re-export logging macros
#[doc(hidden)]
pub use logger::{is_enabled, log_level, LogLevel};

use anyhow::Result;
use std::path::Path;

/// Represents a diagnostic message from linting.
///
/// Diagnostics are generated by lint rules and contain information about
/// code issues including location, severity, and optional fix suggestions.
///
/// # Examples
///
/// ```
/// use woofmt::{Diagnostic, Severity, Fix};
///
/// let diagnostic = Diagnostic {
///     file_path: "main.go".to_string(),
///     line: 10,
///     column: 5,
///     message: "unused import".to_string(),
///     code: "E001".to_string(),
///     severity: Severity::Warning,
///     fix: Some(Fix::safe("Remove unused import", "", 100, 120)),
/// };
/// ```
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Diagnostic {
    /// Path to the file where the diagnostic was found
    pub file_path: String,
    /// Line number (1-indexed)
    pub line: usize,
    /// Column number (1-indexed)
    pub column: usize,
    /// Human-readable message describing the issue
    pub message: String,
    /// Rule code (e.g., "E001", "W101")
    pub code: String,
    /// Severity level of the diagnostic
    pub severity: Severity,
    /// Optional fix suggestion
    pub fix: Option<Fix>,
}

/// Severity level of a diagnostic.
///
/// Used to categorize diagnostics by their importance:
/// - `Error` — Issues that should prevent successful completion
/// - `Warning` — Issues that should be addressed but don't prevent completion
/// - `Info` — Informational messages about code style or suggestions
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Severity {
    /// Critical issue that should be fixed
    Error,
    /// Potential issue that should be reviewed
    Warning,
    /// Informational message
    Info,
}

impl std::fmt::Display for Severity {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Severity::Error => write!(f, "error"),
            Severity::Warning => write!(f, "warning"),
            Severity::Info => write!(f, "info"),
        }
    }
}

/// A fix suggestion for a diagnostic.
///
/// Contains information about how to automatically fix a diagnostic,
/// including the replacement text and the byte range to replace.
///
/// # Examples
///
/// ```
/// use woofmt::Fix;
///
/// let fix = Fix::safe("Remove trailing whitespace", "", 50, 55);
/// ```
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Fix {
    /// Human-readable description of the fix
    pub description: String,
    /// Replacement text (empty string for deletions)
    pub replacement: String,
    /// Start byte position in the source file
    pub start_byte: usize,
    /// End byte position in the source file
    pub end_byte: usize,
    /// Whether the fix may change program semantics.
    ///
    /// Safe fixes (`false`) are purely mechanical (e.g. removing trailing
    /// whitespace) and are applied by `woofmt check --fix` by default.
    /// Unsafe fixes (`true`) can alter behavior and are only applied when
    /// `--unsafe-fixes` is passed.
    pub unsafe_fix: bool,
}

impl Fix {
    /// Create a safe (purely mechanical) fix.
    pub fn safe(
        description: impl Into<String>,
        replacement: impl Into<String>,
        start_byte: usize,
        end_byte: usize,
    ) -> Self {
        Self {
            description: description.into(),
            replacement: replacement.into(),
            start_byte,
            end_byte,
            unsafe_fix: false,
        }
    }

    /// Create an unsafe fix (may change program semantics).
    pub fn unsafe_(
        description: impl Into<String>,
        replacement: impl Into<String>,
        start_byte: usize,
        end_byte: usize,
    ) -> Self {
        Self {
            description: description.into(),
            replacement: replacement.into(),
            start_byte,
            end_byte,
            unsafe_fix: true,
        }
    }
}

/// Run the linter on a file or directory.
///
/// This function scans the specified path for Go files and runs all enabled
/// lint rules, returning a list of diagnostics for any issues found.
///
/// # Arguments
///
/// * `path` — File or directory path to lint
/// * `config` — Configuration settings for the linter
///
/// # Returns
///
/// Returns `Ok(Vec<Diagnostic>)` containing all diagnostics found,
/// or an error if the operation fails.
///
/// # Examples
///
/// ```no_run
/// use woofmt::{lint_path, config::Config};
///
/// let config = Config::default();
/// let diagnostics = lint_path("./src", &config)?;
/// println!("Found {} issues", diagnostics.len());
/// # Ok::<(), anyhow::Error>(())
/// ```
pub fn lint_path<P: AsRef<Path>>(path: P, config: &config::Config) -> Result<Vec<Diagnostic>> {
    linter::lint_path(path, config)
}

/// Format a file or directory.
///
/// Formats Go source files according to the configuration. Can either
/// format in-place or just check if formatting is needed.
///
/// # Arguments
///
/// * `path` — File or directory path to format
/// * `check_only` — If true, only check if formatting is needed without modifying files
/// * `config` — Configuration settings for the formatter
///
/// # Returns
///
/// Returns `Ok(FormatResult)` with statistics about the formatting operation,
/// or an error if the operation fails.
///
/// # Examples
///
/// ```no_run
/// use woofmt::{format_path, config::Config};
///
/// let config = Config::default();
///
/// // Format files in place
/// let result = format_path("./src", false, &config)?;
/// println!("Formatted {} files", result.files_formatted);
///
/// // Check only (CI mode)
/// let result = format_path("./src", true, &config)?;
/// if !result.unchanged {
///     println!("Some files need formatting!");
/// }
/// # Ok::<(), anyhow::Error>(())
/// ```
pub fn format_path<P: AsRef<Path>>(
    path: P,
    check_only: bool,
    config: &config::Config,
) -> Result<FormatResult> {
    formatter::format_path(path, check_only, config)
}

/// Format Go source code string.
///
/// Formats a string containing Go source code and returns the formatted result.
/// This is useful for formatting code in memory without file I/O.
///
/// # Arguments
///
/// * `source` — Go source code string to format
/// * `config` — Configuration settings for the formatter
///
/// # Returns
///
/// Returns `Ok(String)` with the formatted code, or an error if parsing fails.
///
/// # Examples
///
/// ```
/// use woofmt::{format_to_string, config::Config};
///
/// let config = Config::default();
/// let source = r#"package main
///
/// func main() {
/// fmt.Println("Hello")
/// }"#;
///
/// let formatted = format_to_string(source, &config)?;
/// println!("{}", formatted);
/// # Ok::<(), anyhow::Error>(())
/// ```
pub fn format_to_string(source: &str, config: &config::Config) -> Result<String> {
    formatter::format_to_string(source, config)
}

/// Result of a format operation.
///
/// Contains statistics about what was checked and what was changed
/// during a formatting operation.
///
/// # Examples
///
/// ```
/// use woofmt::FormatResult;
///
/// let result = FormatResult {
///     files_checked: 10,
///     files_formatted: 3,
///     unchanged: false,
/// };
///
/// assert_eq!(result.files_checked, 10);
/// assert_eq!(result.files_formatted, 3);
/// assert!(!result.unchanged);
/// ```
#[derive(Debug, Clone)]
pub struct FormatResult {
    /// Total number of files checked
    pub files_checked: usize,
    /// Number of files that were formatted (changed)
    pub files_formatted: usize,
    /// True if no files needed formatting
    pub unchanged: bool,
}
